services:
  postgres:
    image: postgres:16-alpine
    container_name: tijoir-postgres
    environment:
      POSTGRES_DB: tijoir
      POSTGRES_USER: tijoir
      POSTGRES_PASSWORD: tijoir
    ports:
      - "5432:5432"
    volumes:
      - tijoir-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tijoir -d tijoir"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build:
      context: ../../backend
    container_name: tijoir-backend
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/tijoir
      DATABASE_USERNAME: tijoir
      DATABASE_PASSWORD: tijoir
      SPRING_PROFILES_ACTIVE: dev
      AWS_REGION: ${AWS_REGION:-ap-south-1}
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ../../frontend
      args:
        NEXT_PUBLIC_API_BASE_URL: http://localhost:8080
        NEXT_PUBLIC_GOOGLE_CLIENT_ID: 306075557187-cmcq4g3p7rud2ettsuhs8ocl7h3qk9eo.apps.googleusercontent.com
    container_name: tijoir-frontend
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8080
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  tijoir-postgres-data:
