package com.tijoir.audit;

public enum AuditAction {
    SECRET_CREATED,
    SECRET_REVEALED,
    SECRET_REVOKED,
    SECRET_ROTATED,
    SHARE_LINK_CREATED,
    SHARE_LINK_CONSUMED,
    SHARE_LINK_REVOKED,
    VENDOR_CREATED,
    VENDOR_CONTRACT_CREATED,
    VENDOR_CONTRACT_ACCEPTED,
    VENDOR_CONTRACT_REJECTED,
    VENDOR_CONTRACT_REVOKED,
    VENDOR_CONTRACT_GRANT_CREATED,
    VENDOR_CONTRACT_GRANT_REVOKED,
    VENDOR_OFFBOARDED,
    MEMBER_INVITED,
    MEMBER_INVITE_ACCEPTED,
    MEMBER_INVITE_REVOKED,
    MEMBER_ROLE_UPDATED,
    MEMBER_REMOVED,
    ORGANIZATION_POLICY_UPDATED
}
