package com.tijoir.audit;

public enum AuditAction {
    SECRET_CREATED,
    SECRET_REVEALED,
    SECRET_REVOKED,
    SECRET_ROTATED,
    SHARE_LINK_CREATED,
    SHARE_LINK_CONSUMED,
    SHARE_LINK_REVOKED,
    MEMBER_INVITED,
    MEMBER_INVITE_ACCEPTED,
    MEMBER_INVITE_REVOKED,
    MEMBER_ROLE_UPDATED,
    MEMBER_REMOVED
}
