spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:tijoir-test;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false
