package com.tijoir.notification;

public enum NotificationType {
    EMAIL_VERIFICATION,
    EMAIL_VERIFICATION_RESEND,
    ORGANIZATION_INVITE,
    PASSWORD_RESET,
    VENDOR_CONTRACT_PROPOSED,
    VENDOR_CONTRACT_ACCEPTED,
    VENDOR_CONTRACT_REJECTED
}
