"use client";

import { useRouter } from "next/navigation";
import { FormEvent, useEffect, useState } from "react";
import { GuestRoute } from "@/components/auth/auth-guards";
import { AuthShell, StatusPanel } from "@/components/site-chrome";
import { Button } from "@/components/ui/button";
import { BusyOverlay } from "@/components/ui/feedback";
import { PasswordField, TextField } from "@/components/ui/form-fields";
import { useToast } from "@/components/ui/toast-provider";
import { apiRequest, saveSession, type AuthResponse } from "@/lib/auth-client";

export default function InvitePage() {
  const router = useRouter();
  const { showToast } = useToast();
  const [token, setToken] = useState("");
  const [name, setName] = useState("");
  const [password, setPassword] = useState("");
  const [busy, setBusy] = useState(false);

  useEffect(() => {
    if (typeof window === "undefined") {
      return;
    }

    const queryToken = new URLSearchParams(window.location.search).get("token");
    if (queryToken) {
      setToken(queryToken);
    }
  }, []);

  async function acceptInvite(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setBusy(true);

    try {
      const result = await apiRequest<AuthResponse>("/api/organization/invites/accept", {
        method: "POST",
        body: JSON.stringify({ token, name, password }),
      });

      saveSession(result);
      showToast({
        title: "Invite accepted",
        description: "The organization session is ready. Redirecting to the dashboard.",
        tone: "success",
      });
      router.push("/dashboard/overview");
    } catch (error) {
      showToast({
        title: "Invite acceptance failed",
        description: error instanceof Error ? error.message : "Unexpected error",
        tone: "error",
      });
    } finally {
      setBusy(false);
    }
  }

  return (
    <GuestRoute>
      <AuthShell
        aside={
          <div className="space-y-4">
            <StatusPanel
              body="This route completes organization onboarding for invited users. On success it creates the account, verifies it through the invite token, and signs the user in."
              title="Invite flow"
            />
            <StatusPanel
              body="If the invite has expired or was revoked, the token will be rejected before account creation."
              title="Access control"
            />
          </div>
        }
        description="Accept the organization invite, create the user password, and continue directly into the workspace."
        eyebrow="Organization invite"
        title="Join the secure workspace"
      >
        <BusyOverlay
          body="Accepting the organization invite and creating the workspace session."
          title="Joining organization"
          visible={busy}
        />
        <form className="space-y-4" onSubmit={acceptInvite}>
          <div>
            <p className="text-sm font-semibold uppercase tracking-[0.12em] text-(--color-brand-strong)">
              Accept invite
            </p>
            <h2 className="mt-2 text-2xl font-semibold text-(--color-ink-strong)">
              Create the invited user account
            </h2>
            <p className="mt-2 text-sm leading-6 text-muted">
              The invite token already carries the organization and role. You only need to set your visible name and password here.
            </p>
          </div>

          <TextField
            hint="The invite token is generated by the organization manager."
            label="Invite token"
            onChange={setToken}
            value={token}
          />
          <TextField
            hint="This name is shown in the member list and audit context."
            label="Your name"
            onChange={setName}
            value={name}
          />
          <PasswordField
            hint="Use at least 10 characters with a strong mix."
            label="Password"
            onChange={setPassword}
            value={password}
          />

          <div className="flex justify-end">
            <Button disabled={busy} type="submit">
              {busy ? "Joining..." : "Accept invite"}
            </Button>
          </div>
        </form>
      </AuthShell>
    </GuestRoute>
  );
}
